/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pemvismodul5;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lenovo
 */
public class FramePenjualan extends javax.swing.JInternalFrame {
    
    DefaultListModel<String> list1 = new DefaultListModel<>();
    String nama ;
    int pilihan;
    String barang;
    String kode ;
    int harga;
    int total_harga;
    int beli=0;
    int bayar=0;
    int kembali;

    /**
     * Creates new form FramePenjualan
     */
    public FramePenjualan() {
        initComponents();
        listPenjualan.setModel(list1);
        jJumlahBeli.setEditable(false);
        jKembalian.setEditable(false);
        jKodeBarang.setEditable(false);
        jHargaBarang.setEditable(false);
        bSimpan.setText("Simpan");
        tampil_data();
    }
    public void updateJList() {
    listPenjualan.setModel(list1);
    }
    public void reset(){
        jNamaPembeli.setText(null);
        jNamaBarang.setSelectedIndex(0);
        jKodeBarang.setText(null);
        jHargaBarang.setText(null);
        jTotalHarga.setText(null);
        jKembalian.setText(null);
        jBayar.setText(null);
        beli=0;
        jJumlahBeli.setText(null);
        bSimpan.setText("Simpan");
    }
     public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama Pembeli");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Kode Barang");
        tabel.addColumn("Harga Barang");
        tabel.addColumn("Jumlah beli"); 
        tabel.addColumn("Total Harga");
        tabel.addColumn("Total Bayar");
        tabel.addColumn("Kembalian");
        
        try{
            java.sql.Connection conn = pemvismodul5.koneksi.koneksiDB();
            String query="select* from tb_penjualan";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                Object[]row ={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                tabel.addRow(row);
            }
           tJualan.setModel(tabel);
              
       
        }catch(Exception e){
        e.printStackTrace();
    }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jNamaPembeli = new javax.swing.JTextField();
        jNamaBarang = new javax.swing.JComboBox<>();
        jKodeBarang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jHargaBarang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jJumlahBeli = new javax.swing.JTextField();
        bPlus = new javax.swing.JButton();
        bMinus = new javax.swing.JButton();
        jTotalHarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBayar = new javax.swing.JTextField();
        jKembalian = new javax.swing.JTextField();
        bBersih = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tJualan = new javax.swing.JTable();
        bSimpan = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bHitung = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPenjualan = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bBersihkan = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TOKO  PELANGI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jLabel12.setText("Nama Pembeli");

        jLabel13.setText("Nama Barang");

        jLabel14.setText("Kode Barang");

        jNamaBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Buku Gambar", "Buku Tulis", "Cat air", "Crayon", "Penggaris", "Jangka Sorong", "Kertas Lipat", "Tas Punggung", "Gunting", "Mouse", " ", " ", " " }));
        jNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaBarangActionPerformed(evt);
            }
        });

        jLabel15.setText("Harga Barang");

        jHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHargaBarangActionPerformed(evt);
            }
        });

        jLabel16.setText("Jumlah Beli");

        jLabel18.setText("Total Harga");

        jJumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJumlahBeliActionPerformed(evt);
            }
        });

        bPlus.setText("+");
        bPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlusActionPerformed(evt);
            }
        });

        bMinus.setText("-");
        bMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinusActionPerformed(evt);
            }
        });

        jLabel2.setText("Bayar");

        jLabel3.setText("Kembalian");

        bBersih.setBackground(new java.awt.Color(153, 153, 255));
        bBersih.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bBersih.setText("Bersih");
        bBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihActionPerformed(evt);
            }
        });

        tJualan.setBackground(new java.awt.Color(153, 153, 255));
        tJualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pembeli", "Nama Barang", "Kode Barang", "Harga Barang", "Jumlah Beli", "Total Harga", "Bayar", "Kembalian"
            }
        ));
        tJualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tJualanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tJualan);

        bSimpan.setBackground(new java.awt.Color(153, 153, 255));
        bSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(153, 153, 255));
        bReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(153, 153, 255));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bHitung.setBackground(new java.awt.Color(153, 153, 255));
        bHitung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNamaPembeli)
                    .addComponent(jNamaBarang, 0, 256, Short.MAX_VALUE)
                    .addComponent(jKodeBarang)
                    .addComponent(jHargaBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBersih))
                    .addComponent(jTotalHarga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jKembalian))
                .addGap(47, 47, 47))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPlus)
                    .addComponent(bMinus))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bHitung)
                            .addComponent(bBersih))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 674, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Form Penjualan", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane2.setViewportView(listPenjualan);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RIWAYAT PENJUALAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(318, 318, 318))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bBersihkan.setBackground(new java.awt.Color(153, 153, 255));
        bBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bBersihkan.setText("Bersihkan");
        bBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 217, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(bBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(950, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Riwayat Penjualan", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
//      TODO add your handling code here:
        if (bSimpan.getText().equals("Simpan")) {
        String namaPembeli = jNamaPembeli.getText();
        String kode = jKodeBarang.getText();
        String barang = (String) jNamaBarang.getSelectedItem();
        String hargaStr = jHargaBarang.getText();
        String beliStr = jJumlahBeli.getText();
        String bayarStr = jBayar.getText();

    // Pengecekan apakah string kosong
    if (namaPembeli.isEmpty() || kode.isEmpty() || barang.isEmpty() || hargaStr.isEmpty() || beliStr.isEmpty() || bayarStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Lengkapi Semua Data", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        reset();
    } else {
        try {
            // Konversi string menjadi bilangan bulat setelah memastikan tidak kosong
            int harga = Integer.parseInt(hargaStr);
            int beli = Integer.parseInt(beliStr);
            int bayar = Integer.parseInt(bayarStr);
            int total_harga = harga * beli;
            int kembali = bayar - total_harga;

            String sql = "INSERT INTO tb_penjualan (nama_pembeli, nama_barang, kode_barang, harga_barang, jumlah_beli, total_harga, total_bayar, kembalian) VALUES (?,?,?,?,?,?,?,?)";
            java.sql.Connection conn = pemvismodul5.koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, namaPembeli);
            pst.setString(2, kode);
            pst.setString(3, barang);
            pst.setInt(4, harga);
            pst.setInt(5, beli);
            pst.setInt(6, total_harga);
            pst.setInt(7, bayar);
            pst.setInt(8, kembali);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            reset();
            tampil_data();
            String item = namaPembeli + " telah Membeli Barang Dengan Kode " + kode;
            list1.addElement(item);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }
     }if (bSimpan.getText().equals("Edit")) {
    try {
       String update = "UPDATE tb_penjualan SET nama_pembeli=?, nama_barang=?, kode_barang=?, jumlah_beli=?, total_harga=?, total_bayar=?, kembalian=? WHERE nama_pembeli=?";
        java.sql.Connection conn = (java.sql.Connection) pemvismodul5.koneksi.koneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(update);

        // Set nilai parameter sesuai dengan data yang ingin diupdate
        pst.setString(1, jNamaPembeli.getText()); // Update nama_pembeli
        pst.setString(2, jNamaBarang.getSelectedItem().toString()); // Update nama_barang
        pst.setString(3, jKodeBarang.getText()); // Update kode_barang
        pst.setInt(4, Integer.parseInt(jJumlahBeli.getText())); // Ubah sesuai dengan komponen yang sesuai
        pst.setInt(5, Integer.parseInt(jTotalHarga.getText())); // Ubah sesuai dengan komponen yang sesuai
        pst.setInt(6, Integer.parseInt(jBayar.getText())); // Ubah sesuai dengan komponen yang sesuai
        pst.setInt(7, Integer.parseInt(jKembalian.getText())); // Ubah sesuai dengan komponen yang sesuai
        pst.setString(8, jNamaPembeli.getText()); // Kriteria WHERE: nama_pembeli

        pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Edit Berhasil disimpan");
    reset();
    tampil_data(); // Segarkan data di JTable



        // Perbarui model tabel untuk menampilkan data yang diperbarui
        DefaultTableModel model = (DefaultTableModel) tJualan.getModel();
        model.setRowCount(0);  // Hapus semua baris yang ada dalam tabel

        // Tambahkan kembali semua data dari database
        tampil_data();

        list1.addElement("Data pembelian dengan kode " + kode + " telah DiEdit");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal disimpan");
        System.out.println(e.getMessage());
    }
}


String item = jNamaPembeli.getText() + " telah Membeli Barang Dengan Kode " + kode;
list1.addElement(item);

    }//GEN-LAST:event_bSimpanActionPerformed

    private void bBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihActionPerformed
        // TODO add your handling code here:
        if(jKodeBarang.getText().equals("")&&jNamaPembeli.getText().equals("")&&jTotalHarga.getText().equals("")&&jBayar.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Form Input Sudah bersih"); 
        }else {
        reset();
        }
    }//GEN-LAST:event_bBersihActionPerformed

    private void bPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlusActionPerformed
        // TODO add your handling code here:
        beli++;
        jJumlahBeli.setText(Integer.toString(beli));
        total_harga = beli*harga;
        jTotalHarga.setText(""+total_harga);
    }//GEN-LAST:event_bPlusActionPerformed

    private void jJumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJumlahBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJumlahBeliActionPerformed

    private void jHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHargaBarangActionPerformed

    private void jNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaBarangActionPerformed
        // TODO add your handling code here:
        pilihan = jNamaBarang.getSelectedIndex();
        if(pilihan==0){
            reset();
        }

        else if(pilihan==1){
            kode = "01A";
            harga = 7000;
            barang = "Buku Gambar";
        }
        else if(pilihan==2){
            kode = "02B";
            harga = 5000;
            barang = "Buku Tulis";
        }
        else if(pilihan==3){
            kode = "03C";
            harga = 15000;
            barang = "Cat Air";
        }
        else if(pilihan==4){
            kode = "04D";
            harga = 25000;
            barang = "Crayon";
        }
        else if(pilihan==5){
            kode = "05E";
            harga = 3000;
            barang = "Penggaris";
        }
        else if(pilihan==6){
            kode = "06F";
            harga = 12000;
            barang = "Jangka Sorong";
        }
        else if(pilihan==7){
            kode = "07G";
            harga = 8000;
            barang = "Kertas Lipat";
        }
        else if(pilihan==8){
            kode = "08H";
            harga = 75000;
            barang = "Tas Punggung";
        }
        else if(pilihan==9){
            kode = "09I";
            harga = 4000;
            barang = "Gunting";
        }
        else if(pilihan==10){
            kode = "010J";
            harga = 50000;
            barang = "Mouse";
        }
        jKodeBarang.setText(kode);
        jHargaBarang.setText(""+harga);

    }//GEN-LAST:event_jNamaBarangActionPerformed

    private void bMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinusActionPerformed
        // TODO add your handling code here:
        beli--;
       jJumlahBeli.setText(Integer.toString(beli));
         if (beli<0){
       jJumlahBeli.setText("0");
         beli=0;
       }
      
       jJumlahBeli.setText(Integer.toString(beli));
      total_harga = beli*harga;
      jTotalHarga.setText(""+total_harga);
    }//GEN-LAST:event_bMinusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        if(tJualan==null){
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null,"Apakah Yakin Data akan direset?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==0){
        try{
            String sql="delete from tb_penjualan ";
            java.sql.Connection conn=(java.sql.Connection)pemvismodul5.koneksi.koneksiDB();
            java.sql.PreparedStatement 
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            reset();
            tampil_data();
            list1.addElement( "Semua data Telah Di reset ulang (Kosong)");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
            }
        }
    }//GEN-LAST:event_bResetActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        if (tJualan == null) {
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
        } else if (jKodeBarang.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan dihapus!");
        } else {
            int jawab = JOptionPane.showConfirmDialog(null, "Apakah Yakin Data akan dihapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
            // Mendapatkan kode barang yang dipilih
            String kode = jKodeBarang.getText();

            // Query untuk menghapus data dari database
            String sql = "DELETE FROM tb_penjualan WHERE kode_barang = ?";
            java.sql.Connection conn = (java.sql.Connection) pemvismodul5.koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kode);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Berhasil dihapus");
            tampil_data();
            reset();
            list1.addElement("Data pembelian dengan kode " + kode + " telah Dihapus ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }
}
    }//GEN-LAST:event_bHapusActionPerformed

    private void tJualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tJualanMouseClicked
        // TODO add your handling code here:
        int baris = tJualan.rowAtPoint(evt.getPoint());
       
        String a = tJualan.getValueAt(baris, 0).toString();
        jNamaPembeli.setText(a);
        String b = tJualan.getValueAt(baris, 1).toString();
        jNamaBarang.setSelectedItem(b);
        String c = tJualan.getValueAt(baris, 2).toString();
        jKodeBarang.setText(c);
        String d = tJualan.getValueAt(baris, 3).toString();
        jHargaBarang.setText(d);
        String e = tJualan.getValueAt(baris, 4).toString();
        jJumlahBeli.setText(e);
        String f = tJualan.getValueAt(baris, 5).toString();
        jTotalHarga.setText(f);
        String g = tJualan.getValueAt(baris, 6).toString();
        jBayar.setText(g);
        String h = tJualan.getValueAt(baris, 7).toString();
        jKembalian.setText(h);
        bSimpan.setText("Edit");
    }//GEN-LAST:event_tJualanMouseClicked

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
         try {
            int totalBayar = Integer.parseInt(jBayar.getText());
            int totalHarga = Integer.parseInt(jTotalHarga.getText());

            // Menghitung kembalian
            int kembalian = totalBayar - totalHarga;
            jKembalian.setText(Integer.toString(kembalian));
        } catch (NumberFormatException e) {
            jKembalian.setText("Input tidak valid");
        }
    }//GEN-LAST:event_bHitungActionPerformed

    private void bBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihkanActionPerformed
        // TODO add your handling code here:
         if (list1.isEmpty()){
        JOptionPane.showMessageDialog(this,"Data Kosong");
        }else{
        list1.clear();
         }
    }//GEN-LAST:event_bBersihkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBersih;
    private javax.swing.JButton bBersihkan;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bMinus;
    private javax.swing.JButton bPlus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JTextField jBayar;
    private javax.swing.JTextField jHargaBarang;
    private javax.swing.JTextField jJumlahBeli;
    private javax.swing.JTextField jKembalian;
    private javax.swing.JTextField jKodeBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jNamaBarang;
    private javax.swing.JTextField jNamaPembeli;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTotalHarga;
    private javax.swing.JList<String> listPenjualan;
    private javax.swing.JTable tJualan;
    // End of variables declaration//GEN-END:variables
}
